# Generated by Django 5.0.3 on 2024-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb_image',
            field=models.ImageField(blank=True, upload_to='blog/thumbnails/%Y/%m/%d/'),
        ),
    ]
